name: Process Contact Form

on:
  http:
    paths:
      - '/api/contact'
    methods:
      - POST

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install nodemailer

      - name: Send email
        uses: actions/github-script@v7
        with:
          script: |
            const nodemailer = require('nodemailer');
            
            try {
              // Obtener los datos del formulario del payload
              const formData = context.payload;
              
              // Configurar el transporte de email
              const transporter = nodemailer.createTransport({
                service: 'gmail',
                auth: {
                  user: 'stellarteamcr@gmail.com',
                  pass: '${{ secrets.GMAIL_APP_PASSWORD }}'
                }
              });
              
              // Preparar el contenido del email
              const mailOptions = {
                from: 'stellarteamcr@gmail.com',
                to: 'stellarteamcr@gmail.com',
                subject: `Nuevo contacto: ${formData.emailContent.asunto}`,
                html: `
                  <h2>Nuevo mensaje de contacto</h2>
                  <p><strong>Nombre:</strong> ${formData.emailContent.nombre}</p>
                  <p><strong>Email:</strong> ${formData.emailContent.email}</p>
                  <p><strong>Empresa:</strong> ${formData.emailContent.empresa}</p>
                  <p><strong>Servicio:</strong> ${formData.emailContent.servicio}</p>
                  <p><strong>Asunto:</strong> ${formData.emailContent.asunto}</p>
                  <p><strong>Mensaje:</strong></p>
                  <p>${formData.emailContent.mensaje}</p>
                `
              };
              
              // Enviar el email
              await transporter.sendMail(mailOptions);
              
              console.log('Email enviado correctamente');
              
            } catch (error) {
              console.error('Error al enviar el email:', error);
              throw error;
            }
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }} 