name: Process Contact Form

on:
  workflow_dispatch:
  repository_dispatch:
    types: [contact_form_submission]

jobs:
  send-email:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        env:
          GMAIL_APP_PASSWORD: ${{ env.GMAIL_APP_PASSWORD }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: stellarteamcr@gmail.com
          password: ${{ env.GMAIL_APP_PASSWORD }}
          subject: Nuevo contacto desde la web
          html_body: |
            <h2>Nuevo mensaje de contacto</h2>
            <p><strong>Nombre:</strong> ${{ github.event.client_payload.nombre }}</p>
            <p><strong>Email:</strong> ${{ github.event.client_payload.email }}</p>
            <p><strong>Empresa:</strong> ${{ github.event.client_payload.empresa }}</p>
            <p><strong>Servicio:</strong> ${{ github.event.client_payload.servicio }}</p>
            <p><strong>Asunto:</strong> ${{ github.event.client_payload.asunto }}</p>
            <p><strong>Mensaje:</strong></p>
            <p>${{ github.event.client_payload.mensaje }}</p>
          from: stellarteamcr@gmail.com
          to: stellarteamcr@gmail.com
          secure: true 